config/routes.rb
Meritize::Application.routes.draw do

 

  get "results/index"

  resources :nominees
  match '/nominees/:id/status', :to => "nominees#toggled_status"

  resources :props

  resources :prop_displays do
    collection do 
      get :prop_click_more
      post :like_prop
      get  :like_count
    end
  end

  get "props/index"

  get "props/new"

  get "props/edit"

  resources :vote_settings
  resources :votes
  resources :results,:only => [:index] do
     match 'votes', :on=>:collection 
     match 'props', :on=>:collection 
  end
   match '/results/votes/:id/winner' => 'results#winner'
   match '/results/props/:id/prop_winner' => 'results#prop_winner'
   match '/results/props/:id/prop_winner_notify' => 'results#prop_winner_notify'
   match '/results/props/:id/vote_winner_notify' => 'results#vote_winner_notify'
  match '/homes' => 'homes#show'
  root :to => 'sessions#new'
  resources :trial_days
  resources :settings  
  resources :subscriptions do
   match 'history', :on=>:collection
  end
    
    get "paypal/checkout", to: 'subscriptions#paypal_checkout'
    match"/success", :to=> "subscriptions#success", :as => 'success'

  resources :plans
  get "password_resets/new"
  match '/change_password', :controller => 'users', :action => 'change_password'
  match '/reset_confirm', :to =>'password_resets#reset_confirm'
   
  resources :users do
    collection { post :import }
  end

  
  match '/add', :to =>'users#add'
  match '/upload', :to =>'users#upload'
  match '/admin_user', :to =>'users#admin_user'
  match '/adminuser_logs', :to =>'users#adminuser_logs'
  match '/product_manager_logs', :to =>'users#product_manager_logs'
  match '/users/:id/delete', :to => "users#destroy"
  match '/users/:id/status', :to => "users#toggled_status"
  match '/history', :to => "subscriptions#history"
  match '/productadmin_history', :to => "subscriptions#productadmin_history"
  match '/users/validations/check_email', :to=>"users#check_email"
  match '/account_creation', :to =>'users#account_creation'
  match '/suspend', :to =>'users#suspend'
  match '/wows', :to =>'results#wows'
  match '/prop_wows', :to =>'results#prop_wows'
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
  resources :password_resets
  get "/plan" => "subscriptions#plan"
  
  

end

app/models/nominee.rb
class Nominee < ActiveRecord::Base


  attr_accessible :user_id,  :email, :fullname, :role_id, :vote_setting_id, :start_cycle, :end_cycle, :admin_user_id, :firstname, :lastname,:current_user_id, :status

  has_many :users
  accepts_nested_attributes_for :users
  belongs_to :vote_setting  

  has_many :admin_user ,:class_name => 'User'

  validates :email, :presence => true, :uniqueness => true

  validates :user_id, :presence   => true ,:uniqueness => true
   
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
   before_filter :authenticate, :only => [:edit, :update,:index,:show,:new]
  layout :custom_layout
  # GET /nominees
  # GET /nominees.json


   
   def index
      
     @nominees = Nominee.find_all_by_current_user_id(current_user.id)
     @vote_settings = current_user.vote_setting rescue nil
     
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nominees }
      
      @searchuser ||= []
        @adminusers = User.find_all_by_admin_user_id(current_user.id, :conditions => ["firstname || lastname || fullname LIKE ?", "%#{params[:search]}%"])
        @adminusers.each do |adminuser|
        fullname = adminuser.fullname
        @searchuser << fullname
       end
       @searchuser
      
    end
  end


  def toggled_status
        @nominees = User.find(params[:id])
        @nominees.status = !@nominees.status?
        @nominees.save!
        redirect_to nominees_path
  end

  # GET /nominees/1
  # GET /nominees/1.json
  def show
    @nominee = Nominee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nominee }
    end
  end

  # GET /nominees/new
  # GET /nominees/new.json
  def new
    @nominee = Nominee.new
    @searchuser ||= []

    @adminusers = User.where(["firstname || lastname || fullname LIKE ? and id != ? and admin_user_id =? and admin_user_id is not null and status = true", "%#{params[:search]}%",current_user.id,current_user.id])

        @adminusers.each do |adminuser|
          fullname = adminuser.fullname + " (" + adminuser.email + ")"
          @searchuser << fullname
        end

        @searchuser

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nominee }
    end
  end

  # GET /nominees/1/edit
  def edit
    @nominee = Nominee.find(params[:id])
  end

  # POST /nominees
  # POST /nominees.json
  def create
      nominee_params = params[:nominee][:user_id]
      nominee_split = nominee_params.split(" ")

      # There could be spaces in the name. Safest assumption is first array item is partial firstname, and last array element is email
      # "user_id"=>"User 14 Company2 (amoldalvicoursera+local2user14@gmail.com)"}
      nominee_firstname = nominee_split.first rescue nil

      nominee_email1 = nominee_split.last
      nominee_email = nominee_email1.gsub(/[()]/, "") rescue nil
      nominee = User.where(["firstname LIKE ? and email LIKE ? and admin_user_id = ?", "%#{nominee_firstname}%","%#{nominee_email}%", current_user.id])
      if nominee == nil || nominee.length == 0
        flash[:success] = "Sorry, we couldn't locate that user."
         redirect_to :back
       end
      user_id = nominee[0].id
      email = nominee[0].email
      fullname = nominee[0].fullname
      firstname = nominee[0].firstname
      lastname = nominee[0].lastname
      @nominee = Nominee.new(params[:nominee])
      @nominee.user_id = user_id
      @nominee.email = email
      @nominee.fullname = fullname
      @nominee.firstname = firstname
      @nominee.lastname = lastname

     
    if nominee_params.present?
       nomineeemail = User.where('email = ?',nominee_email)
      if nomineeemail.present?
        if @nominee.save
         flash[:success] = "User has been successfully nominated."
         redirect_to :back
      
        else
          redirect_to :back, :notice=> "Please enter all the fields below."
        end
      else
        flash[:notice] = "Sorry, we cannot find that person."
        redirect_to :back 
      end
    else
        redirect_to :back, :notice=> "Please enter all the fields below."
    end
end


  # PUT /nominees/1
  # PUT /nominees/1.json
   
  def update
    @nominee = Nominee.find(params[:id])

    respond_to do |format|
      if @nominee.update_attributes(params[:nominee])
        format.html { redirect_to @nominee, notice: 'Nominee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nominee.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /nominees/1
  # DELETE /nominees/1.json
  def destroy
    @nominee = Nominee.find(params[:id])
    @nominee.destroy
    flash[:success] = "User successfully removed from nominations."
    respond_to do |format|
      format.html { redirect_to nominees_url }
      format.json { head :no_content }
    end
  end


# def check_email
# @nominee = Nominee.find_by_email(params[:nominee][:email])
# respond_to do |format|
    
# format.json { render :json => !@nominee }

# end
# end


def custom_layout
        case action_name
         when "edit"
          "profile"
         when "new"
          "profile"
         when "show"
          "profile"
         when "index"
          "profile"
          
         else
          "application"
        end
    end
private
     #method for deny access if users try to access the pages without login.
    def authenticate
      deny_access unless signed_in?
    end    

end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/nominees/_form.html.erb
<%= stylesheet_link_tag "application"%>

  <div id="info">
  <div class="container">
 

        <%= form_for(@nominee) do |f| %> 
      <div class="row"></div>
      
      


      <div class="container">
      <h1>Add Nominee</h1>
       <table class="table table-hover table-responsive table-condensed">
       <tbody>     
       


            
    
           
            <tr>
              <td>  
                <label class="control-label">Start Cycle</label>
              </td>
              <td>
         
               <%= select("nominee", "start_cycle", VoteSetting.find_all_by_user_id(current_user.id).collect {|p| [ p.start_cycle.strftime("%d %B %Y"), p.start_cycle ] }, {}, :class=>"form-control") %>
              </td>
            </tr>


            <tr>
              <td>  
               <label class="control-label">End Cycle</label>
              </td>
              <td>
            

              <%= select("nominee", "end_cycle", VoteSetting.find_all_by_user_id(current_user.id).collect {|p| [ p.end_cycle.strftime("%d %B %Y"), p.end_cycle ] }, {}, :class=>"form-control") %>

              <%= f.hidden_field :current_user_id ,:value => current_user.id %>
              
              <%= f.hidden_field :status ,:value => true %>
              </td>
            </tr>

             
                      
            <tr>
              <td>
               <label class="control-label">I Nominate</label>
               </td>
               <td>
            
               <%= f.text_field :user_id, :class => "form-control1" %></br>

           
               </td>
            </tr>
                  <% if @nominee.errors.any? %>
                      <div id="error_explanation">

                          <ul>
                            <% @nominee.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                          </ul>
                      </div>
                  <% end %>

               </td>
            </tr>


             <div class = "field">
            <%= f.hidden_field :admin_user_id , :value => current_user.id %>
            <%= f.hidden_field :firstname, :value => @users %>
            <%= f.hidden_field :lastname, :value => @users  %>
             </div>

     <tr>
     <td></td>
      <td>
        <%= f.submit "Add", :class => "btn btn-primary"%>
      </td>
     </tr>      
    
      <% end %>
       </tbody>
    </table>
   </div>   
</div>


<script>
    var data = <%= raw @searchuser %>;

    jQuery(function() {

      jQuery( "#nominee_user_id" ).autocomplete(
      {
         source:data
      });


        
    });
    </script>


       <%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>  
       

app/views/nominees/edit.html.erb
<h1>Editing nominee</h1>

<%= render 'form' %>

<%= link_to 'Show', @nominee %> |
<%= link_to 'Back', nominees_path %>

app/views/nominees/index.html.erb
  <script>
  var data = <%= raw @searchuser %>;


  jQuery(function() {

    jQuery( "#search" ).autocomplete(
    {
       source:data
    });
      
  });
  </script>



  <div id="info">   
      
      <div class="container" style="margin-bottom:100px">

      <div class="jumbotron">
        <p>Use this page to nominate who can win the <%= @vote_settings.award_program_name %> award. You don't have to have nominees. If you don't have any nominees, your voters can vote for any user. If you do have nominees, your voters will have to vote for one of the nominees.</p>
      </div>



    <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Manage Nominees</a>
          </div>
         
            <ul class="nav navbar-nav">
              
                 <form class="navbar-form navbar-left">
                  <div class="form-group">

                  <%= link_to "Add new Nominee" , new_nominee_path(:type =>"adminuser"), :class_name => nil,:class=> "button button-small"%>


                    

                     </div>
                   </form>
        
              <li class="pull-right">
            
              </li>

            </ul>
       
         </div>
      </div>




<h4>Nominees for voting cycle: <%= @vote_settings.start_cycle.strftime("%d %B %Y") rescue nil%>&nbsp;to&nbsp;<%= @vote_settings.end_cycle.strftime("%d %B %Y") rescue nil%></h4>
<table class="table table-hover table-bordered table-responsive table-condensed">
<thead>
  <tr>        

              
              <th>Name</th>
              <th>Email</th>
              <th>Status</th>
              <th align="center">Action</th>    
  </tr>
  </thead>
  <tbody>

        <% @nominees.each do |nominee| %>
        
        <tr>
          <td><%= nominee.fullname %></td>
          <td><%= nominee.email %></td>
          <td><% if nominee.status%>Active<% else %>User has been inactivated<% end %></td>
          
          <td align="center">



        <%= link_to 'Remove From Nominee', nominee, method: :delete, data: { confirm: 'Are you sure?' },:class=>  "btn btn-primary"  %> 

         </td>

        </tr>
          <% end %>
   </tbody>
</table>


    </div>  
  </div>

app/views/nominees/indexbackup.html.erb
 <%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>

  <%= stylesheet_link_tag "dashboard.css" %>
 

   <script type="text/javascript"> 
      jQuery(document).ready( function() {
        jQuery('#deletesuccess').delay(10000).fadeOut();
      });
    </script>

  <script>
  var data = <%= raw @searchuser %>;


  jQuery(function() {

    jQuery( "#search" ).autocomplete(
    {
       source:data
    });
      
  });
  </script>



  <div id="info">   
      
      <div class="container">

     

      <div class="jumbotron">
        <p>Use this page to nominate who can win the award. You don't have to have nominees. If you don't have any nominees, your voters can vote for any voter. If you do have nominees, your voters will have to vote for one of the nominees.</p>
        <p><a class="btn btn-primary btn-lg">Learn more</a></p>
      </div>

      





      

    <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Manage Nominee</a>
          </div>
         
            <ul class="nav navbar-nav">
              
                 <form class="navbar-form navbar-left">
                  <div class="form-group">

                  <%= link_to "Add new Nominee" , new_nominee_path(:type =>"adminuser"), :class_name => nil,:class=> "button button-small"%>
                    

                     </div>
                   </form>
        
              <li class="pull-right">
            <form class="navbar-form navbar-left">
                  <div class="form-group">

                    <%= form_tag admin_user_path, :method => 'get',:html =>{:id =>"edit-profile",:class=> "form-horizontal"}  do %>

                    <%= text_field_tag :search, params[:search], :class=>"form-control" %>    <%= submit_tag "Search", :class_name => nil,:class=> "button button-small"%>

                     <% end %>
                     </div>
                   </form>
              </li>
            </ul>
       
         </div>
      </div>







<h3>Nominees</h3>
<table class="table table-hover table-bordered table-responsive table-condensed">
<thead>
  <tr>        <!-- <th>Vote Cycle</th>      -->


              <th>User Name</th>
              <th>User Email</th>
              <th></th>    
  </tr>
  </thead>
  <tbody>

        <% @nominees.each do |nominee| %>
        
        <tr>
         

          <td><%= nominee.fullname %></td>
          <td><%= nominee.email %></td></br>

          <td align="center">
          
         <%= link_to format_boolean(nominee.status?), {:controller => 'nominees', :action => 'toggled_status', :id => nominee.id} %> 
         </td>

        </tr>
          <% end %>
   </tbody>
</table>


    </div>  
  </div>

app/views/nominees/new.html.erb
<%= render 'form' %>
<!-- 
<%= link_to 'Back', nominees_path %>
 -->

app/views/nominees/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <b>Start Cycle:</b>
  <%= @nominee.start_cycle %> 
  <b>End Cycle:</b> 
  <%= @nominee.end_cycle %> 
</p>


<p>

  <b>User Name:</b>
  <%= @nominee.fullname %>  
</p>

<p>
  <b>User Email:</b>
  <%= @nominee.email %>  
</p>


<%= link_to 'Edit', edit_nominee_path(@nominee) %> |

<%= link_to 'Add', nominees_path %>