config/routes.rb
Meritize::Application.routes.draw do

 

  get "results/index"

  resources :nominees
  match '/nominees/:id/status', :to => "nominees#toggled_status"

  resources :props

  resources :prop_displays do
    collection do 
      get :prop_click_more
      post :like_prop
      get  :like_count
    end
  end

  get "props/index"

  get "props/new"

  get "props/edit"

  resources :vote_settings
  resources :votes
  resources :results,:only => [:index] do
     match 'votes', :on=>:collection 
     match 'props', :on=>:collection 
  end
   match '/results/votes/:id/winner' => 'results#winner'
   match '/results/props/:id/prop_winner' => 'results#prop_winner'
   match '/results/props/:id/prop_winner_notify' => 'results#prop_winner_notify'
   match '/results/props/:id/vote_winner_notify' => 'results#vote_winner_notify'
  match '/homes' => 'homes#show'
  root :to => 'sessions#new'
  resources :trial_days
  resources :settings  
  resources :subscriptions do
   match 'history', :on=>:collection
  end
    
    get "paypal/checkout", to: 'subscriptions#paypal_checkout'
    match"/success", :to=> "subscriptions#success", :as => 'success'

  resources :plans
  get "password_resets/new"
  match '/change_password', :controller => 'users', :action => 'change_password'
  match '/reset_confirm', :to =>'password_resets#reset_confirm'
   
  resources :users do
    collection { post :import }
  end

  
  match '/add', :to =>'users#add'
  match '/upload', :to =>'users#upload'
  match '/admin_user', :to =>'users#admin_user'
  match '/adminuser_logs', :to =>'users#adminuser_logs'
  match '/product_manager_logs', :to =>'users#product_manager_logs'
  match '/users/:id/delete', :to => "users#destroy"
  match '/users/:id/status', :to => "users#toggled_status"
  match '/history', :to => "subscriptions#history"
  match '/productadmin_history', :to => "subscriptions#productadmin_history"
  match '/users/validations/check_email', :to=>"users#check_email"
  match '/account_creation', :to =>'users#account_creation'
  match '/suspend', :to =>'users#suspend'
  match '/wows', :to =>'results#wows'
  match '/prop_wows', :to =>'results#prop_wows'
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
  resources :password_resets
  get "/plan" => "subscriptions#plan"
  
  

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password


   attr_accessible :username, :email, :password, :password_confirmation,:role_ids, :user_id,:username, :firstname, :lastname,:plan_id,:plan_type,:companyname, :hear_aboutus,:admin_user_id,:photo,:time_zone,:fullname, 
                   :plan_name,:department,:is_prop,:is_prop_reminder,:is_vote_reminder,:agree,:department
   has_attached_file :photo,:styles =>{:micro => "30x30#", :small => "150x150>"},
  :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml",
  :path => "public/attachments/user/:id/:style/:basename.:extension",
  :convert_options => {
                          :thumb => "-background '#F7F4F4' -compose Copy -gravity center -extent 230x200"
                      }
   validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
   has_and_belongs_to_many :roles

   has_one :plan

   has_one :setting 
   belongs_to :nominee 
   has_many :prop_counts
   has_many :results
   has_many :prop_results
   has_many :engage_users
   has_many :vote_counts
   has_many :vote_other_counts
   has_one :settings  
   has_one :prop
   has_one :vote_setting
   has_one :setting
   belongs_to :trial_day
 
   belongs_to :admin_user ,:class_name => 'User' 


  #model based validation
   # validates :firstname, :presence => true, 
   #                :length => { :maximum => 50 }
   email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email,:uniqueness => { :case_sensitive => false },:presence => { :message => " cannot be blank" }

    validates :password,  :confirmation => true,:on => :create

   before_save :encrypt_password
   before_create { generate_token(:auth_token) }

  
   
    acts_as_liker
    
    #method for password reset
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

    #method for generating authentication token. 
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

   #Method for trial days for admin
  def self.admin_user_plan_expiry(user)     
      @trial_days = TrialDay.first     
      @admin_user_plan_expiry = (user.created_at + @trial_days.days.days)
      @current_date = (Time.zone.now)
      @remaining_days = (@admin_user_plan_expiry - @current_date).to_i / 1.day       
  end


  class << self
  def authenticate(email, submitted_password)
  user = find_by_email(email)
  (user && user.has_password?(submitted_password)) ? user :nil

  end

  def authenticate_with_salt(id,cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user :nil
  end 
  end
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end




def self.to_csv
      CSV.generate do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
end








def self.import(file, current_user)  

  current_user = current_user.id #admin current id

  CSV.foreach(file.path, skip_blanks: true, headers: true) do |row|
    @random_password = (0..6).map{ ('a'..'z').to_a[rand(26)] }.join
    add = row.to_hash

    @check_user = User.find_by_email(add['email'])
    if @check_user.present?
      @check_user.update_attributes(:firstname => add['firstname'],:lastname => add['lastname'],:department => add['department'], :fullname => add['firstname'] + ' ' + add['lastname'])
    else
      @user = User.create(:firstname => add['firstname'],:lastname => add['lastname'],:email =>add['email'],:department => add['department'],:role_ids => 3 ,:password =>@random_password ,:password_confirmation =>@random_password,:admin_user_id => current_user, :fullname => add['firstname'] + ' ' + add['lastname'], :is_prop => true, :is_vote_reminder => true, :is_prop_reminder => true)
      if @user.save
        UserMailer.uploaduser_verifymail(@user,@random_password).deliver
      end
    end
#    if @user.save
#      @user.update_column(:fullname,"#{[:firstname]} #{[:lastname]} ")
#      UserMailer.delay(run_at: 1.minutes.from_now).uploaduser_verifymail(@user,@random_password)
#    end
  end
end










      
  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password) unless password.nil? 
   end

  def encrypt(string)
  secure_hash("#{salt}--#{string}")
  end

  def make_salt
  secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
  Digest::SHA2.hexdigest(string)
  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate, :only => [:edit, :update,:dashboard,:admin_user,:adminuser_logs,:suspend,:product_manager_logs,:change_password,:show,:upload]
   before_filter :correct_user, :only => [:show]
  
   layout :custom_layout
   require 'will_paginate/array'
   require 'csv'

    

  def show
    @user = User.find(params[:id])

  end

  def new

    #@random generates random value which wiil be used for generating temparay password.
    @random = (0..6).map{ ('a'..'z').to_a[rand(26)] }.join
    @user = User.new
    @title="Sign up"

  end

   def dashboard
      # @users = User.all
      @plans = Plan.all
      @trial_days = TrialDay.first
      @user = User.find_by_id(current_user)
      @plan_expiry = plan_expiry
     
   end
   # this method allows admin to activate or deactivate users
   def toggled_status
        @users = User.find(params[:id])
        @users.status = !@users.status?
        @users.update_column(:status,@users.status)
        @users.update_column(:updated_at,Time.zone.now)
        # Update Nominee status as well 
        @nominee = Nominee.find_by_user_id(params[:id])
        unless @nominee.nil?
          @nominee.status = @users.status
          @nominee.updated_at = Time.zone.now
          @nominee.save
        end
        redirect_to :back
        UserMailer.user_status_mail(@users).deliver         
    end
   
    def suspend
       @user = User.where("username is null  and admin_user_id is null").paginate :page => params[:page],:per_page => 10

    end


   def account_creation

   end

   #method for searching a admin_user and showing list of admin_user
   def admin_user         
       @plan_expiry = plan_expiry
        @searchuser ||= []
        @adminusers = User.find_all_by_admin_user_id(current_user.id, :conditions => ["firstname || lastname || fullname LIKE ?", "%#{params[:search]}%"], :order => 'fullname ASC, email ASC').paginate :page => params[:page],:per_page => 10

        @adminusers.each do |adminuser|        
        fullname = adminuser.fullname
        @searchuser << fullname
       end
       @searchuser   
   end

   

 #method for Upload CSV
def import 
   if params[:file].blank? 
      flash[:error] = 'Please Upload File.'
      redirect_to upload_path      
   else 
     AdminuserLog.import(params[:file],current_user.id)    
     @user = User.import(params[:file],current_user)
     redirect_to admin_user_path, notice: "Users imported." 
     
    end
 end





   #method for searching a adminuser_logs and showing list of adminuser_logs

   def adminuser_logs
       @searchuser ||= []
       @adminusers = AdminuserLog.find_all_by_admin_user_id(current_user.id, :conditions => ["firstname || lastname || fullname LIKE ?", "%#{params[:search]}%"],:order => "created_at DESC").paginate :page => params[:page],:per_page => 10
       @adminusers.each do |adminuser|
        fullname = adminuser.fullname
        @searchuser << fullname       
       end
       @searchuser
   end




   def product_manager_logs
       @searchuser ||= []
       @adminusers = ProductManagerLog.find(:all, :conditions => ["firstname || lastname || fullname LIKE ?", "%#{params[:search]}%"],:order => "created_at DESC").paginate :page => params[:page],:per_page => 10
       @adminusers.each do |adminuser|
        fullname = adminuser.fullname
        @searchuser << fullname
       end
       @searchuser
   end

  #method for create new_user and sending them verification emails.
def create
      @user = User.new(params[:user])
       @random_password = params[:user][:password]
       
      if @user.save
        @user.update_column(:fullname,"#{params[:user][:firstname]} #{params[:user][:lastname]}")
         UserVerification.welcome_email(@user,@random_password).deliver            
         if params[:page_name] == "admin" 

           redirect_to admin_user_path ,:flash => {:notice => "User successfully created and temporary password sent to user."}
         elsif params[:page_name] == "user"

          # Set default settings
          # Amol May 2014
          @setting = Setting.new(
            :company_name => @user.companyname, 
            :description => 'Enter description about your company', 
            :website_address => 'www.mycompanywebsite.com',
            :user_id => @user.id)
          core_values = @setting.core_values.build(
            :title => 'Excellence',
            :description => 'Strive for excellence at every juncture and deliver excellent results to our customers')
          core_values = @setting.core_values.build(
            :title => 'Respect',
            :description => 'Treat each other with respect and conduct ourselves with utmost integrity')
          core_values = @setting.core_values.build(
            :title => 'Innovation',
            :description => 'Be open to new ideas and push each other to find new solutions to age-old problems')
          core_values = @setting.core_values.build(
            :title => 'Passion',
            :description => 'Do what we love and love what we do')
          if @setting.save
            # do nothing, all good
          else
            logger.info @setting.errors.full_message
          end

          @todaysdate = Date.today
          @VoteSetting = VoteSetting.new(
            :award_frequency_type => 'Monthly', 
            :award_program_name => 'Employee of the month',
            :start_cycle => @todaysdate,
            :end_cycle => (@todaysdate >> 1) - 1, 
            :intro_text => "Who's rocking it? Who's the one person that stands head and shoulders above everyone else? Who's gone that extra mile? Who deserves to be the Employee of the Month?", 
            :user_id => @user.id,
            :email_sender_name => @user.firstname + ' ' + @user.lastname,
            :email_sender_email => @user.email,
            :email_sender_subject1 => "It's time to vote",
            :email_sender_body1 => 'Hello dear colleague. Take a minute and vote for employee of the month. Click here to login with your email address: http://www.imeritize.com',
            :email_sender_subject2 => 'We need you',
            :email_sender_body2 => 'Yes, we really do! Or more like your colleagues do. They want to know who you think did the best this past month. Take a minute and vote for the employee of the month. Click here and login with your email address: http://www.imeritize.com',
            :email_sender_subject3 => 'Remember when you voted?',
            :email_sender_body3 => "I don't either! Take a minute and vote for the employee of the month. Click here and login with your email address: http://www.imeritize.com",
            :is_autopick_winner => 'f',
            :is_admin_reminder => 't', 
            :is_allow_vote => 't', # Disallow voters to vote for last time's winner
            :reminder1_days => 5,
            :reminder2_days=> 10,
            :reminder3_days => 20)
          if @VoteSetting.save
            # do nothing, all good
          else
            logger.info @VoteSetting.errors.full_message
          end

          @PropsSetting = Prop.new(
            :enable => 't', 
            :assign_points => 't', 
            :start_point => 1,
            :step_point => 1, 
            :end_point => 3, 
            :reset_point => 1, # never let points expire 
            :start_cycle => @todaysdate, 
            :end_cycle => (@todaysdate >> 1) - 1, 
            :intro => "Ah, team work. It's so good to know someone has your back. Someone who can answer that tough question for you or pick up a sandwich for you while you power through lunch. Or simply hear you out while you vent. Send them some props. It will bring a smile to their face.", 
            :name => @user.firstname + ' ' + @user.lastname, 
            :email => @user.email, 
            :body => "It feels great to get props. And it feels even better when you give them out. We'd appreciate it if you could spread them around. Click here and login with your email address: www.imeritize.com", 
            :body2 => "Hey. Sorry to bug you again. But we noticed you haven't given props in a while. You know how the world works - what goes around comes around. So give some props today. Click here and login with your email address: www.imeritize.com", 
            :body3 => "Now hear ye, hear ye. We know you know that you like to be appreciated. It's not about the money. Well, it is. So let me rephrase. It's not all about the money. Think, my friend, think. Who are you thankful for? Click here and login with your email address: www.imeritize.com", 
            :subject => "Props, praise, kudos and high-fives", 
            :subject2 => "The sweet smell of props", 
            :subject3 => "No excuses", 
            :reminder1_days => 5,
            :reminder2_days => 10,
            :reminder3_days => 20,
            :user_id => @user.id)
          if @PropsSetting.save
            # do nothing, all good
          else
            logger.info @PropsSetting.errors.full_message
          end

          # Even if settings weren't saved, send user to confirmation message screen because the user was created
          redirect_to account_creation_path, :flash => {:notice => "Hello, #{@user.firstname}. Your brand new Meritize account is ready.
          We have sent your instructions for getting started to your email address.
          Contact us at support@imeritize.com if you have any questions."}
        else
           redirect_to admin_user_path ,:flash => {:notice => "User successfully created and temporary password sent to user."}
        end
   
      else

        @random = (0..6).map{ ('a'..'z').to_a[rand(26)] }.join

        @title = "Sign Up"
        render 'new'
      end
   end 



# Moved to scheduler.rake for Heroku scheduler
=begin
  def self.reminder_email           
          admin_user = User.where("username is null  and admin_user_id is null")          
          admin_user.each do |user| 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account_creation.html.erb
<%= javascript_include_tag "jquery-1.5.2.min","jquery.validate.min","validation" %>

<body id="signup">
<div class="row">
      <div class="col-md-12">
        <div class="wrapper clearfix">
          <div class="formy">
            <div class="row">
              <div class="col-md-12">
          

           
            <div class="form-group">
           
            <section class="round">
                      <% flash.each do |key, value| %>
                    <div class="flash <%= key %>" style = "font-size:18px; text-align:center;"><%= value %></div>
                    <% end %>
            </section>

               
              
               <div class="submit">
              <%= link_to "Login", signin_path,:class =>"button-clear" %> 
              </div> 
              


            </div>


</div>            
  </div>

app/views/users/add.html.erb
<div id="info">
		<div class="container">
      <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Manage Users</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to "Add" , add_path%>
              </li>
              <li>
                <%= link_to "Upload" , upload_path%>
              </li>
              
            </ul>
          </div>
        </div>
      </div>
      
        <table class="table table-hover table-bordered table-responsive table-condensed">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name <font color="red">*</font>
              </th>
              <th>Last Name <font color="red">*</font>
              </th>
              <th>Email <font color="red">*</font>
              </th>
              <th>Role <font color="red">*</font>
              </th>
              <th>Username <font color="red">*</font>
              </th>
              <th>Department</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td></td>
              <td>
                <input type="text" class="form-control">
              </td>
              <td>
                <input type="text" class="form-control">
              </td>
              <td>
                <input type="text" class="form-control">
              </td>
              <td>
                <select class="form-control">
                  <option>Voter</option>
                  <option>Admin</option>
                </select>
              </td>
              <td><input type="text" class="form-control"></td>
              <td>
                <input type="text" class="form-control">
              </td>
              <td>
                <a class="button button-small">Save</a>
              </td>
            </tr>
          </tbody>
        </table>
      
      <hr>
      
    </div>
	</div>

app/views/users/admin_user.html.erb
  <%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>

  <%= stylesheet_link_tag "dashboard.css" %>
 

   <script type="text/javascript"> 
      jQuery(document).ready( function() {
        jQuery('#deletesuccess').delay(10000).fadeOut();
      });
    </script>

  <script>
  var data = <%= raw @searchuser %>;


  jQuery(function() {

    jQuery( "#search" ).autocomplete(
    {
       source:data
    });
      
  });
  </script>




  
     <div class="container" style="margin-bottom:100px">
  <div id="deletesuccess">
        
          <% if current_user.role? :productmanager %>
           <ul>
               Welcome  <%= current_user.firstname %> <%= current_user.lastname %><br/><br/>
   
             
          <% elsif current_user.role? :admin %>
            <% unless  current_user.plan_type == "premium" %> 
            Only <%= @plan_expiry %> days left for your trial plan to expire. You can upgrade at any time.
            <% end %>
         <% else %>
           User Name: <%= current_user.firstname %> <%= current_user.lastname %><br/>
           Email:<%= current_user.email %><br/>
        <% end %>
        
    </div>

    <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Manage Users</a>
          </div>
          <div class="collapse navbar-collapse">
            
          </div>
         
            <ul class="nav navbar-nav">
              
                 <form class="navbar-form navbar-left">
                  <div class="form-group">

                  <%= link_to "Add new User" , new_user_path(:type =>"adminuser"), :class_name => nil,:class=> "button button-small"%>
                        

                     </div>
                   </form>
        
              <li class="pull-right">
            <form class="navbar-form navbar-left">
                  <div class="form-group">

                    <%= form_tag admin_user_path, :method => 'get',:html =>{:id =>"edit-profile",:class=> "form-horizontal"}  do %>
      
                    <%= text_field_tag :search, params[:search], :class=>"form-control" %>  <%= submit_tag "Search", :class_name => nil,:class=> "button button-small"%>


                     <% end %>
                     </div>
                   </form>
              </li>
            </ul>
       
         </div>
      </div>




      
      <table class="table table-hover table-bordered table-responsive table-condensed">
  <tr>
    <th>#</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Department</th>
    <th colspan="2">Action</th>
    <th>Activate/Deactivate</th>
  </tr>
  <% @adminusers.each.with_index(1) do |adminusers,index| %>
  <tr>
    <td><%= index %></td>
    <td><%= adminusers.firstname rescue nil %></td>
    <td><%= adminusers.lastname rescue nil%></td>
    <td><%= adminusers.email rescue nil%></td>
     <td><%= adminusers.department rescue nil%></td>
    <td><%= link_to "Edit" , edit_user_path(adminusers,:type=>"adminuser") ,:class=>  "btn btn-primary" %></td>
    <td><a href="/users/<%= adminusers.id %>/delete" onclick="if(confirm('Are you sure you want to delete this user?'))  return true;  else  return  false;" class = "btn btn-primary" >Delete</a>

 </td>
    <td><%= link_to format_boolean(adminusers.status?), {:controller => 'users', :action => 'toggled_status', :id => adminusers.id} %></td>
  </tr>
   <% end %>
</table>
  <div align="right">
           <ul class="pagination"> <li><%= will_paginate @adminusers  %></li></ul>
  </div>
        
        
      
      <hr>
      
   
  </div>

</div>

app/views/users/adminuser_logs.html.erb
<%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>
<script>
var data = <%= raw @searchuser %>;


jQuery(function() {

  jQuery( "#search" ).autocomplete(
  {
     source:data
  });
    
});
</script>

 <div id="info">
     <div class="container" style="margin-bottom:100px">
    <section class="round">
        <% flash.each do |key, value| %>
      <div class="flash <%= key %>" style = "font-size:18px;"><%= value %></div>
      <% end %>
  </section>



  <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">User Activities</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
           
              
        
              <li class="pull-right">
            <form class="navbar-form navbar-left">
                  <div class="form-group">
                    <%= form_tag adminuser_logs_path, :method => 'get',:html =>{:id =>"edit-profile",:class=> "form-horizontal"} do %>
                      <%= text_field_tag :search, params[:search], :class=>"form-control" %>

                     <%= submit_tag "Search", :class_name => nil,:class=> "button button-small" %>
                     <% end %>
                     </div>
                   </form>
              </li>
            </ul>
          </div>
        </div>
      </div>
     
           


        
         <table class="table table-bordered table-striped table-highlight">
            <thead>
              <tr>
                
                
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Login Time</th>
                <th>Logout Time</th>
                <th>IP Address</th>
               
               
              </tr>
            </thead>
            <% @adminusers.each do |adminusers| %>
            <tbody>
              <tr>
                             
                <td><%= adminusers.firstname rescue nil %></td>
                <td><%= adminusers.lastname rescue nil%></td>
                <td><%= adminusers.email rescue nil %></td>
                <td><%= adminusers.sign_in_time.strftime("%e %b %Y %H:%m") rescue nil%></td>
                <td><%= adminusers.sign_out_time.strftime("%e %b %Y %H:%m") rescue nil%></td>
                <td><%= adminusers.ip_address rescue nil%></td>
                
              </tr>
              
            </tbody>
            <% end %>
          </table>
            <div align="right">
           <ul class="pagination"> <li><%= will_paginate @adminusers  %></li></ul>
          </div>

           
        </div>

        </div>
  </div>

app/views/users/new.js.erb
<% unless @adminusers.blank? %>
    $('.endless_scroll_inner_wrap').append("<%=escape_javascript(render :partial => 'post', :collection => @adminusers)%>");
    $('ul').attr('last', '<%=@adminusers.to_a.last.created_at%>')
<% else %>
    $('#infinite-scroll').detach();
<% end %>

app/views/users/product_manager_logs.html.erb
<%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css" %>
<script>
var data = <%= raw @searchuser %>;


jQuery(function() {

  jQuery( "#search" ).autocomplete(
  {
     source:data
  });
    
});
</script>

 <div id="info">
     <div class="container" style="margin-bottom:100px">
    <section class="round">
        <% flash.each do |key, value| %>
      <div class="flash <%= key %>" style = "font-size:18px;"><%= value %></div>
      <% end %>
  </section>



  <div class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Product Manager Activities</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
           
              
        
              <li class="pull-right">
            <form class="navbar-form navbar-left">
                  <div class="form-group">
                    <%= form_tag product_manager_logs_path, :method => 'get',:html =>{:id =>"edit-profile",:class=> "form-horizontal"} do %>
                      <%= text_field_tag :search, params[:search], :class=>"form-control" %>

                     <%= submit_tag "Search", :class_name => nil,:class=> "button button-small" %>
                     <% end %>
                     </div>
                   </form>
              </li>
            </ul>
          </div>
        </div>
      </div>
     
           


        
         <table class="table table-bordered table-striped table-highlight">
            <thead>
              <tr>
                
                <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Login Time</th>
                <th>Logout Time</th>
                <th>Ip Address</th>
                
               
              </tr>
            </thead>
            <% @adminusers.each do |adminusers| %>
            <tbody>
              <tr>
                
                <td><%= adminusers.email rescue nil %></td>
                <td><%= adminusers.firstname rescue nil %></td>
                <td><%= adminusers.lastname rescue nil%></td>
                <td><%= adminusers.sign_in_time.strftime("%e %b %Y %H:%m") rescue nil%></td>
                <td><%= adminusers.sign_out_time.strftime("%e %b %Y %H:%m") rescue nil%></td>
                <td><%= adminusers.ip_address rescue nil%></td>
               
              </tr>
              
            </tbody>
            <% end %>
          </table>
           <div align="right">
           <ul class="pagination"> <li><%= will_paginate @adminusers  %></li></ul>
          </div>
        </div>

        </div>
  </div>