config/routes.rb
Meritize::Application.routes.draw do

 

  get "results/index"

  resources :nominees
  match '/nominees/:id/status', :to => "nominees#toggled_status"

  resources :props

  resources :prop_displays do
    collection do 
      get :prop_click_more
      post :like_prop
      get  :like_count
    end
  end

  get "props/index"

  get "props/new"

  get "props/edit"

  resources :vote_settings
  resources :votes
  resources :results,:only => [:index] do
     match 'votes', :on=>:collection 
     match 'props', :on=>:collection 
  end
   match '/results/votes/:id/winner' => 'results#winner'
   match '/results/props/:id/prop_winner' => 'results#prop_winner'
   match '/results/props/:id/prop_winner_notify' => 'results#prop_winner_notify'
   match '/results/props/:id/vote_winner_notify' => 'results#vote_winner_notify'
  match '/homes' => 'homes#show'
  root :to => 'sessions#new'
  resources :trial_days
  resources :settings  
  resources :subscriptions do
   match 'history', :on=>:collection
  end
    
    get "paypal/checkout", to: 'subscriptions#paypal_checkout'
    match"/success", :to=> "subscriptions#success", :as => 'success'

  resources :plans
  get "password_resets/new"
  match '/change_password', :controller => 'users', :action => 'change_password'
  match '/reset_confirm', :to =>'password_resets#reset_confirm'
   
  resources :users do
    collection { post :import }
  end

  
  match '/add', :to =>'users#add'
  match '/upload', :to =>'users#upload'
  match '/admin_user', :to =>'users#admin_user'
  match '/adminuser_logs', :to =>'users#adminuser_logs'
  match '/product_manager_logs', :to =>'users#product_manager_logs'
  match '/users/:id/delete', :to => "users#destroy"
  match '/users/:id/status', :to => "users#toggled_status"
  match '/history', :to => "subscriptions#history"
  match '/productadmin_history', :to => "subscriptions#productadmin_history"
  match '/users/validations/check_email', :to=>"users#check_email"
  match '/account_creation', :to =>'users#account_creation'
  match '/suspend', :to =>'users#suspend'
  match '/wows', :to =>'results#wows'
  match '/prop_wows', :to =>'results#prop_wows'
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
  resources :password_resets
  get "/plan" => "subscriptions#plan"
  
  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :company_name, :description, :website_address,
                  :user_id,:photo,:core_values_attributes
  belongs_to :user
  has_many :core_values,:dependent => :destroy
  accepts_nested_attributes_for :core_values, :allow_destroy => true 
  has_attached_file :photo,:styles =>{:small => "150x150>"},
  :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml",
  :path => "public/attachments/setting/:id/:style/:basename.:extension",
  :convert_options => {
                          :thumb => "-background '#F7F4F4' -compose Copy -gravity center -extent 230x200"
                      }
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  layout 'profile'
  before_filter :authenticate, :only => [:edit, :update,:index,:show,:new]
  before_filter :correct_user, :only => [:edit, :update,:show,:new]
  
  def index
    @settings = Setting.find_by_user_id(current_user.id)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new
    3.times do

      core_values = @setting.core_values.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to edit_setting_path(@setting), notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to edit_setting_path(@setting), notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
 private
  #method for deny access if users try to access the pages without login.
  def authenticate
    deny_access unless signed_in?
  end
   #method for deny access if users try to access user details.
  def correct_user
    @user = User.find(current_user)
    redirect_to("/dashboard",:notice => 'You cannot access this page') unless current_user == @user && current_user.role?(:admin)
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_core_value_fields.html.erb
                  <div class = "fields">
	                  <div class="col-md-4">
	                   
	                    <%= f.text_field :title ,:class=>"form-control", :maxlength => 25 %>
	                  </div>
	                  <div class="col-md-8">
	                    <%= f.text_area :description,:rows =>3,:class=>"form-control" %>
	                    <%= link_to_remove_fields "remove", f %>
	                    
	                  </div>
                   </div>
           
              

app/views/settings/_form.html.erb
<div id="info">
<div class="container" style="margin-bottom:100px">
      

        <%= form_for @setting ,:html => {:multipart => true} do |f| %>
        <% if @setting.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

            <ul>
            <% @setting.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
       

        <h1>Settings - General</h1>
        <table class="table table-hover table-responsive table-condensed">
          <tbody>
            <tr>
              <td>
                <label class="form-label">Company name:</label>
              </td>
              <td>
                 <%= f.text_field :company_name,:class=>"form-control" %>
                 <%= f.hidden_field :user_id , :value => current_user.id %>
              </td>
            </tr>
            <tr>
              <td>
                <label class="form-label">Company logo:</label>
              </td>
              <td>
                
                <% if params[:action] == "edit" %>
                <div style ="float:left;margin-left:-65px;width:auto;">
                  <%= image_tag @setting.photo.url(:small) %>
               </div>
                <% end %>

               <div style="float:left;margin:25px 0 0 15px" id="file_tag"> 
                <span><%= f.file_field :photo%>Current File</span>         
               </div>



              </td>
            </tr>
            <tr>
              <td>
                <label class="form-label">Website address:</label>
              </td>
              <td>
                 <%= f.text_field :website_address,:class=>"form-control" %>
              </td>
            </tr>
            <tr>
              <td>
                <label class="form-label">Core values:</label><br/>(No more than 10)
              </td>
              <td>
                <div class="row">

                    <%= f.fields_for :core_values do |builder| %>
            
                          <%= render "core_value_fields", :f => builder %>
            
                    <% end %>
                
                              
                  <%= link_to_add_fields "Add another core value", f, :core_values %>
                
                </div>
              </td>
            </tr>
              <tr>
              <td>
                
              </td>
              <td>
                  <%= f.submit "Save", :class => "btn btn-primary"%>
               
              </td>
            </tr>



          </tbody>
        </table>
        <% end %>
      </div>

  

  <script type='text/javascript'>//<![CDATA[ 
$(window).load(function(){
$('#button').click(function () {
    $("input[type='file']").trigger('click');
})

$("input[type='file']").change(function () {
    $('#val').text(this.value.replace(/C:\\fakepath\\/i, ''))
})
});//]]>  

</script>

app/views/settings/edit.html.erb
<%= render 'form' %>

app/views/settings/index.html.erb
<% # This page and controller is not used. %>
<% # Commented out everything and added a line "Access Denied" for security reasons. %>
<p align="center">Access denied</p>

<!--<h1>Listing settings</h1>

<table border="1">
  <tr>
    <th>Company name</th>
    <th>Website address</th>
     <th>Company Logo</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <tr>
    <td><%= @settings.company_name rescue nil%></td>
    <td><%= @settings.website_address rescue nil%></td>
    <td><%= image_tag @settings.photo.url(:small) rescue nil %></td>
    
    
    <% unless @settings.nil?%>
    <td><%= link_to 'Show', @settings %></td><br/>
    <td><%= link_to 'Edit', edit_setting_path(@settings) %></td>
    <% end %>
  </tr>

</table>

<br />
<% if @settings.nil?%>
  <%= link_to 'New Setting', new_setting_path %>
<% end %>
-->

app/views/settings/new.html.erb
<%= render 'form' %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @setting.company_name %>
</p>

<p>
  <b>Website address:</b>
  <%= @setting.website_address %>
</p>

<p>
  <b>Description:</b>
  <%= @setting.description %>
</p>


<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>