config/routes.rb
Meritize::Application.routes.draw do

 

  get "results/index"

  resources :nominees
  match '/nominees/:id/status', :to => "nominees#toggled_status"

  resources :props

  resources :prop_displays do
    collection do 
      get :prop_click_more
      post :like_prop
      get  :like_count
    end
  end

  get "props/index"

  get "props/new"

  get "props/edit"

  resources :vote_settings
  resources :votes
  resources :results,:only => [:index] do
     match 'votes', :on=>:collection 
     match 'props', :on=>:collection 
  end
   match '/results/votes/:id/winner' => 'results#winner'
   match '/results/props/:id/prop_winner' => 'results#prop_winner'
   match '/results/props/:id/prop_winner_notify' => 'results#prop_winner_notify'
   match '/results/props/:id/vote_winner_notify' => 'results#vote_winner_notify'
  match '/homes' => 'homes#show'
  root :to => 'sessions#new'
  resources :trial_days
  resources :settings  
  resources :subscriptions do
   match 'history', :on=>:collection
  end
    
    get "paypal/checkout", to: 'subscriptions#paypal_checkout'
    match"/success", :to=> "subscriptions#success", :as => 'success'

  resources :plans
  get "password_resets/new"
  match '/change_password', :controller => 'users', :action => 'change_password'
  match '/reset_confirm', :to =>'password_resets#reset_confirm'
   
  resources :users do
    collection { post :import }
  end

  
  match '/add', :to =>'users#add'
  match '/upload', :to =>'users#upload'
  match '/admin_user', :to =>'users#admin_user'
  match '/adminuser_logs', :to =>'users#adminuser_logs'
  match '/product_manager_logs', :to =>'users#product_manager_logs'
  match '/users/:id/delete', :to => "users#destroy"
  match '/users/:id/status', :to => "users#toggled_status"
  match '/history', :to => "subscriptions#history"
  match '/productadmin_history', :to => "subscriptions#productadmin_history"
  match '/users/validations/check_email', :to=>"users#check_email"
  match '/account_creation', :to =>'users#account_creation'
  match '/suspend', :to =>'users#suspend'
  match '/wows', :to =>'results#wows'
  match '/prop_wows', :to =>'results#prop_wows'
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  root :to => 'sessions#new'
    match 'dashboard' => 'users#dashboard', :as => 'user_root'
    match '/signup', :to =>'users#new'
    match '/signin', :to =>'sessions#new'
    match  '/users/:id/edit',  :to => "users#edit" 
    match '/signout', :to =>'sessions#destroy'
  resources :password_resets
  get "/plan" => "subscriptions#plan"
  
  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :name, :price, :user_id, :description1, :description2, :description3,:forusers, :foradmins, :pricing
  belongs_to :user
  has_many :subscriptions
  has_many :payment_notifications
end

app/controllers/plans_controller.rb
 class PlansController < ApplicationController
   before_filter :authenticate, :only => [:edit, :update,:index,:show,:new]
   layout "profile"
  # GET /plans
  # GET /plans.json
  def index
  	
    @plans = Plan.order(:id)
    @plan_expiry = plan_expiry 
    @subscription = Subscription.find_by_user_id(current_user) 
      # raise current_user.id.inspect
    respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @plans }

    end
  end

 def show
    @plan = Plan.find(params[:id])
        
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }

    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plans_path, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])
   
    respond_to do |format|
      if @plan.update_attributes(params[:plan])

        format.html { redirect_to plans_path, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
      deny_access unless signed_in?
    end

    def plan_params
    params.require(:plan).permit(:description1, :description2,:description3)
  end
end

app/helpers/plans_helper.rb
module PlansHelper

end

app/views/plans/_form.html.erb
 <script type="text/javascript"></script> <script type="text/javascript">
//<![CDATA[
bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
//]]>
</script>
<div id="masthead">
  
  <div class="container">
    
    <div class="masthead-pad">
      
      <div class="masthead-text">
        <h2>Manage Plans</h2>
        
      </div> <!-- /.masthead-text -->
      
    </div>
    
  </div> <!-- /.container --> 
  
</div> <!-- /#masthead -->


<div id="content">

    <div class="container" style="margin-bottom:100px">   
    
      
    <table class="table table-responsive">
      <tbody >
       <%= form_for (@plan) do |f|  %>   
       <tr>
       <td  width="20%">                     
        <label  class="form-label">Plan name</label>
       </td>
       <td>
       <%= f.text_field :name ,:class=>"form-control" %> 
       </td>
       </tr>  
                           
      
        <tr>
        <td>   
        <label class="form-label">Price</label>
        </td>
        <td>
        <%= f.text_field :price,:class=>"form-control" %>
        </td>
        </tr>
       
                  
        
        <tr>
        <td>                       
        <label for="email" class="control-label"> All Users </label>
        </td>
        <td>
          <%= f.text_area :forusers, cols: 100, rows: 15,:class=>"form-control"%>
         
        
        </td>
        </tr>
       
        
        <tr>
        <td>                       
        <label for="email" class="control-label">Admin Users</label>
        </td>
        <td>
        <%= f.text_area :foradmins, cols: 100, rows: 15,:class=>"form-control" %>
        </td>
        </tr>
      

        
        <tr>
        <td>                       
        <label for="email" class="control-label">Pricing</label>
        </td>
        <td>
        <%= f.text_area :pricing, cols: 100, rows: 15,:class=>"form-control" %>
        </td>
        </tr>
    

       
        <tr>
        <td>
        <label class="form-actions"></label>
        </td>
        <td>
         <%= f.submit 'Update',:class=> "button button-primary", :id => "submit_plan" %>
        </td>
        </tr>
    
        <% end %>     
        </tbody>
        </table>
        </div> <!-- /.container -->
      </div> <!-- /#content -->

app/views/plans/edit.html.erb
<%= render 'form' %>

app/views/plans/index.html.erb
<%= stylesheet_link_tag "dashboard.css" %>
<%= javascript_include_tag "jquery.js" %>

 <div id="info">
  <div class="container">
  <% if current_user.role? :productmanager %>
      <ul>
        Welcome <%= current_user.firstname %> <%= current_user.lastname %><br/><br/>
  <% elsif (current_user.role? :admin) && (plan_expiry <= 0) && (current_user.plan_type == "free")%>
      Your trial period has expired. Please select a paid plan to continue using Meritize.
  <% elsif (current_user.role? :admin) && (plan_expiry >= 0) && (current_user.plan_type == "free") %>
     <div id="deletesuccess" class="jumbotron">
      Only <%= plan_expiry %> days left for your trial plan to expire. You can upgrade at any time.
     </div>
  <% else %>
     
  <% end %>
</div>
a
  

  <div id="first-option">

    <div class="container" style="margin-bottom:100px" >

  <% if current_user.role? :productmanager %>
  <table class="table table-bordered table-striped table-highlight">
  <thead>
  <tr>
  <th>Name</th>
  <th>Price</th>
  <th>All User</th>
  <th>All Admin</th>
  <th>Pricing</th>
  <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @plans.each do |plan| %>
<tr>
  <td><%= plan.name %></td>
  <td><%= plan.price %></td>
  <td><%= plan.forusers.try(:html_safe) %></td>
  <td><%= plan.foradmins.try(:html_safe) %></td>
  <td><%= plan.pricing.try(:html_safe) %></td>
  <td><%= link_to 'Edit', edit_plan_path(plan),:class=> "btn btn-primary" %></td>
 </tr>
 <% end %>
</tbody>
</table>
<% elsif current_user.role? :admin%>

  <h1>Plans</h1>
<table style = "width:100%;">
  <% @plans.each do |plan| %>
  <% if @subscription.nil? %>
  <tr>
  <td align="left" valign="top" style="width:33.33%">
  <table class="table table-hover table-bordered table-responsive table-condensed">
  <tr>
  <th><h2 style="text-align:center; margin-top:10px"><%= plan.name %></h2></th>
  </tr>
  <tr>
   <td style="height:190px"><%= plan.forusers.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="height:171px"><%= plan.foradmins.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="height:90px"><%= plan.pricing.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="padding-bottom: 39px; padding-top: 20px;text-align:center">
  <% @subscription = plan.subscriptions.build %>
  <%= link_to image_tag("/assets/paypal.png"),paypal_checkout_path(plan_id: @subscription.plan_id) %></td>
  </tr>
  </table>

  </td>

  <% else %>

  <td align="left" valign="top" style="width:33.33%"><table class="table table-hover table-bordered table-responsive table-condensed">
  <tr>
  <th> <h2 style="text-align:center; margin-top:10px"><%= plan.name %></h2></th>
  </tr>
  <tr>
  <td style="height:190px"><%= plan.forusers.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="height:171px"><%= plan.foradmins.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="height:90px"><%= plan.pricing.try(:html_safe) %></td>
  </tr>
  <tr>
  <td style="padding-bottom: 39px; padding-top: 20px;">                        
  <% subscription = plan.subscriptions.build %>
  <% if @subscription.plan_id == plan.id%>
  <a class="button button-small" href="#"> <span>Current Plan</span> </a>
  <% else %>
  <%= link_to image_tag("/assets/paypal.png"),paypal_checkout_path(plan_id:subscription.plan_id) %> 
  <% end %>

  </td>
  </tr>
  </table>
  </td>

  <% end %>
  <% end %>

  </tr>

  </table>
  <% end %>
  </div>
  </div>
  </div>


  <script type="text/javascript"> 
      $(document).ready( function() {
        $('#deletesuccess').delay(10000).fadeOut();
      });
    </script>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/plan_backup.html.erb
<!-- Select Plan From This Page -->
<div id="masthead">
	
	<div class="container">
		
		<div class="masthead-pad">
			
			<div class="masthead-text">
				<h2>Plan</h2>
				
			</div> <!-- /.masthead-text -->
			
		</div>
		
	</div> <!-- /.container -->	
	
</div> <!-- /#masthead -->




<div id="content">

	<div class="container">
		
		
		<div class="row" >
			
			<div class="span12" style="margin-left:150px">
				
				
				<div class="pricing-plans plans-4">

		<% if current_user.role? :productmanager %>

					<div id="content">

	                 <div class="container">
      
                       <table class="table table-bordered table-striped table-highlight">
                            <thead>
                           <tr>
                             <th>Name</th>
                             <th>price</th>
                             <th>description1</th>
                             <th>description2</th>
                             <th>description3</th>
                             <th></th>
                             <th></th>
                          </tr>
                           </thead>
                     <tbody>
          	<% @plans.each do |plan| %>

         
            <tr>
                   <td><%= plan.name %></td>
                   <td><%= plan.price %></td>
                   <td><%= plan.description1 %></td>
                   <td><%= plan.description2 %></td>
                   <td><%= plan.description3 %></td>
                   <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
                   <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
                <% end %>
         
          </tbody>
        </table>
      </div> <!-- /.container -->

</div> <!-- /#content -->

</div> <!-- /#wrapper -->




			<% elsif current_user.role? :admin%>
                      	
				
				    <body>
	<div id="content">

		<div class="price-chart">
			
			<div class="pt-table">	
				<div class="pt-body">
					<ul class="pt-rows">
				  <% @plans.each do |plan| %>
				  	 <% if @subscription.nil? %>

						<li class="title"><%= plan.name %></li>
						<li class="fees"><%= plan.price %></li>	
						<li class="fees"><%= plan.description1 %></li>
						<li class="fees"><%= plan.description2 %></li>
						<li class="fees"><%= plan.description2 %></li>	
											
						<li>
						<span class="pt-no">							
						<% @subscription = plan.subscriptions.build %>
						<%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(plan_id: @subscription.plan_id) %>
						</span>

                       <% else %>

                         <li class="title"><%= plan.name %></li>
						<li class="fees"><%= plan.price %></li>	
						<li class="fees"><%= plan.description1 %></li>
						<li class="fees"><%= plan.description2 %></li>
						<li class="fees"><%= plan.description2 %></li>	
											
						<li>
						<span class="pt-no">							
						<% subscription = plan.subscriptions.build %>
						<% if @subscription.plan_id == plan.id%>
						Current Plan 
						<% else %>
						<%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(plan_id: subscription.plan_id) %>
						<% end %>
						</span>

                      
					<% end %>
				<% end %>
						</li>
						
					</ul>
				</div>
				
			</div>
		</div>
		
</div>
</body></html>

				   <% end %>

				</div>
				
			</div> <!-- /.span12 -->
			
		</div> <!-- /.row -->
		
		
	</div> <!-- /.container -->

</div> <!-- /#content -->

</div> <!-- /#wrapper -->










<script>

$(function () {
	
	Theme.init ();
	
});

</script>

</body>
</html>

                               

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>

<p>
  <b>Price:</b>
  <%= @plan.price %>
</p>

<%= link_to "Checkout", @plan.paypal_url(subscriptions_url, payment_notifications_url) %>
<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>